language: go
go:
  - 1.9.x
env:
  - CC_TEST_REPORTER_ID=38d8bbf824319af70da37f7713988e0b16f121529e6788ff122b49cfec43d8ec
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/modocache/gover
  - ./cc-test-reporter before-build
intstall:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure
script:
  - go test -cover -coverpkg github.com/ildarusmanov/adfsuserinfo -coverprofile adfsuserinfo.coverprofile      .
  - go test -cover -coverpkg github.com/ildarusmanov/adfsuserinfo/services -coverprofile services.coverprofile ./services
  - go test -cover -coverpkg github.com/ildarusmanov/adfsuserinfo/controllers -coverprofile controllers.coverprofile ./controllers
  - go test -cover -coverpkg github.com/ildarusmanov/adfsuserinfo/models -coverprofile models.coverprofile ./models
after_script:
  - gover ./ c.out
  - ./cc-test-reporter after-build -t gocov --exit-code $TRAVIS_TEST_RESULT

